# Generated by Django 2.2 on 2019-06-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190411_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoryId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
