# Generated by Django 2.2 on 2019-06-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
    ]
